spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL:false}

rate-limiter:
  fallback-strategy: AP

logging:
  level:
    com.ratelimiter: INFO
